package triersistemas.estagio_back_end.enuns;

public enum ProdutoOrderEnum {
    ID_DEC,
    ID_ASC,
    CODIGO_BARRAS_DEC,
    CODIGO_BARRAS_ASC,
    NOME_DEC,
    NOME_ASC,
    DESCRICAO_DEC,
    DESCRICAO_ASC,
    TIPO_PRODUTO_DEC,
    APRESENTACAO_DEC,
    MARGEM_LUCRO_DEC,
    VALOR_PRODUTO_DEC,
    SITUACAO_CADASTRO_DEC,
    TIPO_PRODUTO_ASC,
    APRESENTACAO_ASC,
    MARGEM_LUCRO_ASC,
    VALOR_PRODUTO_ASC,
    SITUACAO_CADASTRO_ASC,
    VALOR_VENDA_DEC,
    VALOR_VENDA_ASC
}
